name: Hello World
on: 
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Dí Hola
        run: echo "Hello World Diego Ruiz"

  Tarea2:
    runs-on: ubuntu-latest

    steps:
      - name: Fecha Sistema
        run: echo "Bienvenidos a mi primer desafio" echo "La fecha de hoy es:" date

        
